### ISSUE TITLE
"Promo" Asset Type 

### ISSUE THREAD

**Issue by aabn** [sroosa/AAPB_Cataloging#13]
The "Promo" asset type display as "PRomo." When I go back in to re-edit the record, it disappears from the selected asset type.
cpb-aacip/305-77fqzdrq

**Comment by sroosa** [comment]
I think this is an issue of what the exact string that the system has in it's database is (probably "PRomo"), and what the exact string saved on the drop down menu is ("Promo"). Since they don't match, when you go to re-edit the record, the system deletes the "PRomo" string because it is not one of the exact strings in the drop down menu. Hopefully changing the string saved in the database from "PRomo" to "Promo," will fix the problem.
