### ISSUE TITLE
Contributor Field Bug?

### ISSUE THREAD

**Issue by careymacd92** [sroosa/AAPB_Cataloging#21]
The system keeps automatically making one of my contributors a "film director." I deleted that contributor and added it again, and it's doing the same thing. May be a temporary bug? I will check on it again next week.

For now it seems like the system wants to promote that one panelist :)!

cpb-aacip/257-83kwhhvs

**Comment by sroosa** [comment]
The AMS seems to be adding "film director" as an affiliation with the contributor, so he still has "Panelist" as his role. The reason it's doing that is because there is an entry for someone with the same name that has "film director" as their affiliation. And so the system thinks it's being really smart and saying "oh, the last time someone used this guy's name his affiliation was "film director," so you must want that here too." Of course, that's not what we want. We haven't yet figured out a way to prevent the affiliations from following the contributor names, so for now you can just leave it. The nice thing is the when the data from the AMS gets harvested for the AAPB website, affiliations don't appear on the website, so the incorrect data won't show up to the public at least.

**Comment by careymacd92** [comment]
I see - thank you!!
